CREATE TABLE IF NOT EXISTS role (
  id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(255) NOT NULL UNIQUE, descricao VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
INSERT IGNORE INTO role (nome, descricao) VALUES ('tutor', NULL), ('aluno', NULL), ('coordenador', NULL), ('juri', NULL), ('administrador', NULL);
CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT PRIMARY KEY, fullname VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, telefone VARCHAR(20), idade INT NOT NULL DEFAULT 17, genero VARCHAR(10), role_id INT, n_processo VARCHAR(50), curso VARCHAR(50), area_formacao VARCHAR(50), n_mecanografico VARCHAR(50), password VARCHAR(255) NOT NULL, password_expires_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_user_role_id (role_id)
);
CREATE TABLE IF NOT EXISTS area_formacao (
  id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(50) NOT NULL, descricao VARCHAR(255), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS curso (
  id INT AUTO_INCREMENT PRIMARY KEY, nome VARCHAR(50) NOT NULL, descricao VARCHAR(255), area_formacao_id INT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_curso_area_formacao_id (area_formacao_id)
);
CREATE TABLE IF NOT EXISTS estudante (
  id INT AUTO_INCREMENT PRIMARY KEY, id_user INT, numero_estudante INT NOT NULL, numero_processo VARCHAR(50), turma VARCHAR(15), ano_lectivo VARCHAR(15), id_curso INT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_estudante_id_user (id_user), INDEX idx_estudante_id_curso (id_curso)
);
CREATE TABLE IF NOT EXISTS professor (
  id INT AUTO_INCREMENT PRIMARY KEY, id_user INT NOT NULL, especializacao VARCHAR(50), categoria VARCHAR(50), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_professor_id_user (id_user)
);
CREATE TABLE IF NOT EXISTS tcc (
  id INT AUTO_INCREMENT PRIMARY KEY, tema VARCHAR(255) UNIQUE, objectivo VARCHAR(255), estado DOUBLE NOT NULL DEFAULT 0, data_submissao TIMESTAMP NULL DEFAULT NULL, id_estudante INT NOT NULL, id_professor INT NOT NULL, relatorio_pdf VARCHAR(255), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_tcc_id_estudante (id_estudante), INDEX idx_tcc_id_professor (id_professor)
);
CREATE TABLE IF NOT EXISTS banca (
  id INT AUTO_INCREMENT PRIMARY KEY, data VARCHAR(20), sala INT NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS defesa (
  id INT AUTO_INCREMENT PRIMARY KEY, id_tcc INT NOT NULL, id_banca INT NOT NULL, data_defesa VARCHAR(50) NOT NULL, resultado VARCHAR(20) NOT NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_defesa_id_tcc (id_tcc), INDEX idx_defesa_id_banca (id_banca)
);
CREATE TABLE IF NOT EXISTS subdireccao (
  id INT AUTO_INCREMENT PRIMARY KEY, id_user INT, cargo VARCHAR(255), created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS app_session (
  id VARCHAR(255) PRIMARY KEY, data MEDIUMTEXT NOT NULL, expires_at DATETIME NOT NULL, INDEX idx_app_session_expires_at (expires_at)
);
